image: archlinux
packages:
  - git
  - go
secrets:
  - a4a77b05-94e0-443c-9408-b2d81f7263fe
  - b15309e0-8156-44c8-aa7c-58c0f0b7d503
sources:
  - https://git.sr.ht/~poldi1405/go-yenc
tasks:
  - mirror-to-github: |
      git clone --mirror https://git.sr.ht/~poldi1405/go-yenc
      cd go-yenc.git
      git push --mirror git@github.com:mpldr/go-yenc.git
  - setup: |
      cd go-yenc
      go test -v -cover -race .
